// All themed ("lore layer") copy lives here so it can be audited, localised,
// or toned down in one place. Rules (see CLAUDE.md): restraint — one themed
// word per screen; every themed label carries a plain explanation; error
// messages are always plain and never themed.
export const copy = {
  appName: 'Minos',
  tagline: 'Every query gets judged.',

  update: {
    available: (v: string) => `Minos v${v} is available.`,
    whatsNew: "What's new",
    howTo: (method: string) => `To upgrade (${method}):`,
    copy: 'Copy command',
    copied: 'Upgrade command copied.',
  },

  nav: {
    dashboard: { label: 'The Tribunal', hint: 'dashboard' },
    querylog: { label: 'The Docket', hint: 'query log' },
    devices: { label: 'Devices', hint: 'clients & groups' },
    lists: { label: 'The Codex', hint: 'blocklists' },
    domains: { label: 'Pardons & Sentences', hint: 'allow & deny domains' },
    settings: { label: 'Settings', hint: 'server configuration' },
  },

  stats: {
    judged: 'Judged',
    judgedHint: 'total queries handled',
    condemned: 'Condemned',
    condemnedHint: 'blocked queries',
    blockRate: 'Block rate',
    blockRateHint: 'share of queries blocked',
    rules: 'Rules',
    rulesHint: 'compiled block rules',
    cacheRate: 'Cache hits',
    cacheRateHint: 'answers served from memory, no upstream trip',
  },

  dashboard: {
    timelineTitle: 'Queries — last 24 hours',
    topBlockedTitle: 'Most condemned domains',
    topBlockedHint: 'most-blocked, last 24 hours',
    topClientsTitle: 'Busiest clients',
    topClientsHint: 'by query count, last 24 hours',
    noData: 'No query data yet.',
  },

  docket: {
    title: 'The Docket',
    subtitle: 'live query log',
    empty: 'No queries yet. Point a device at this resolver and its fate appears here.',
    verdictBlocked: 'condemned', // API value: "blocked"
    verdictAllowed: 'passed', //    API value: "allowed"
    searchPlaceholder: 'Filter by domain or client…',
    filterAll: 'All verdicts',
    filterBlocked: 'Condemned only',
    filterAllowed: 'Passed only',
    filterWouldBlock: 'Would block only',
    wouldBlockBadge: 'would block',
    wouldBlockTitle: (list: string, rule: string) =>
      `An audit-mode list would have condemned this: "${rule}" in ${list}. Not enforced.`,
    deviceScope: 'device', // prefixes the drilled-in device's IP(s) chip
    live: 'live',
  },

  pardon: {
    action: 'Pardon',
    actionHint: 'always allow this domain',
    done: (domain: string) => `${domain} pardoned — always allowed from now on.`,
  },

  sentence: {
    action: 'Sentence',
    actionHint: 'always block this domain',
    done: (domain: string) => `${domain} sentenced — always blocked from now on.`,
  },

  recess: {
    action: 'Recess',
    actionHint: 'pause blocking',
    resume: 'Resume blocking',
    active: (until: string) => `Blocking paused until ${until}.`,
    activeIndefinite: 'Blocking paused.',
    headerPill: 'In recess',
  },

  lists: {
    title: 'The Codex',
    subtitle: 'subscribed blocklists',
    empty: 'No blocklists configured. Add one below.',
    refreshAll: 'Refresh all lists',
    refreshing: 'Refreshing…',
    addTitle: 'Add a list',
    allowBadge: 'allowlist',
    allowBadgeTitle:
      'Every entry on this list is always allowed, beating every blocklist — a subscribed pardon.',
    actionBlock: 'blocklist — entries are blocked',
    actionAllow: 'allowlist — entries are always allowed',
    confirmDelete: (name: string) =>
      `Remove the list "${name}"? Its rules stop applying immediately.`,
    auditHeader: 'Audit',
    auditTitle:
      "Audit mode: this list's rules are logged as 'would block' in the Docket but never enforced — try a strict list safely, then untick to enforce it.",
    auditBadge: 'audit',
    auditBadgeTitle: 'Logged as "would block", never enforced.',
    servicesTitle: 'Blocked services',
    servicesHint: 'one click blocks a whole service for every device',
    servicesNote:
      'Blocking a service here applies to everyone. To block one only for certain devices, or only at certain times of day, set the service on a group instead — groups can carry a schedule and are assigned to devices on the',
    servicesNoteLink: 'Devices page.',
    serviceDomains: (n: number) => `${n} domain${n === 1 ? '' : 's'}`,
  },

  domains: {
    checkTitle: 'Judge a domain',
    checkHint: 'see which rule decides its fate',
    checkPlaceholder: 'example.com',
    checkButton: 'Judge',
    checkBlocked: (list: string, rule: string) => `Condemned — matched "${rule}" in ${list}.`,
    checkAllowedByRule: (rule: string) => `Passed — pardoned by "${rule}".`,
    checkAllowed: 'Passed — no rule matches; it would be forwarded upstream.',
    pardonsTitle: 'Pardons',
    pardonsHint: 'domains always allowed (and their subdomains)',
    pardonsEmpty: 'No pardons granted.',
    servicePardonsTitle: 'Service pardons',
    servicePardonsHint: 'one click always allows everything a service needs',
    servicePardonsNote:
      'Pardoning a service allows it for every device, including the extra playback and sign-in domains streaming apps need. A pardon beats any sentence or blocklist. To pardon a service only for certain devices, set it on a group on the',
    servicePardonsNoteLink: 'Devices page.',
    sentencesTitle: 'Sentences',
    sentencesHint: 'domains always blocked (and their subdomains)',
    sentencesEmpty: 'No standing sentences.',
    addPlaceholder: 'domain to add…',
    localTitle: 'Local DNS',
    localHint: 'names answered here — never blocked, never sent upstream',
    localEmpty: 'No local records. Add one to name a device or service on your network.',
    localNamePlaceholder: 'nas.home.lab or *.home.lab',
    localValuePlaceholder: (t: string) =>
      t === 'CNAME' ? 'target.home.lab' : 'address (comma-separate several)',
    localAdd: 'Add record',
    localWildcardNote: 'A leading *. matches all subdomains. Address records also answer reverse (PTR) lookups.',
  },

  devices: {
    title: 'Devices',
    subtitle: 'every client that queries this resolver',
    empty: 'No devices yet. Point something at this resolver and it appears here.',
    neverSeen: 'never',
    blockAction: 'Block DNS',
    blockHint: 'refuse all DNS from this device',
    unblockAction: 'Unblock',
    blockedBadge: 'DNS blocked',
    namePlaceholder: 'label…',
    groupDefault: 'default (full rules)',
    groupsTitle: 'Groups',
    groupsHint: 'device policies — assign devices above',
    groupsEmpty: 'No groups. Devices follow the default rules until you create one.',
    modeFilter: 'filter — default rules plus this group’s lists',
    modeBypass: 'bypass — no filtering at all',
    modeBlock: 'block — refuse all DNS',
    addTitle: 'Create a group',
    extraAllow: 'Extra pardons (always allow)',
    extraDeny: 'Extra sentences (always block)',
    groupServices: 'Blocked services for this group',
    groupAllowedServices: 'Service pardons for this group',
    groupSafeSearch: 'Enforce Safe Search for this group',
    scheduleSummary: 'Schedule',
    scheduleOn: (start: string, end: string) => `active ${start}–${end}`,
    scheduleNote:
      'The group applies only during these hours (server time); outside them its devices follow the default rules. An end before the start runs past midnight.',
    scheduleSet: 'Set schedule',
    scheduleClear: 'Remove schedule',
    listPlaceholder: 'comma-separated domains',
    confirmDelete: (name: string) =>
      `Delete the group "${name}"? Its devices fall back to the default rules.`,
    forget: 'Forget',
    forgetHint: 'remove the saved label/group for this device',
    viewInDocket: 'View this device’s queries in the Docket',
    activityHint: 'show what this device queried',
    activityTitle: (hours: number) =>
      hours >= 168 ? 'activity, last 7 days' : `activity, last ${hours} hours`,
    activityTotals: (total: number, blocked: number) =>
      `${total.toLocaleString()} queries, ${blocked.toLocaleString()} blocked`,
    activityAllowed: 'Top allowed domains',
    activityBlocked: 'Top blocked domains',
    activityEmpty: 'Nothing in this window.',
    activityLoading: 'Loading…',
  },

  settings: {
    title: 'Settings',
    save: 'Save changes',
    saved: 'Settings saved and applied — no restart needed.',
    upstreamsTitle: 'The Ferrymen',
    upstreamsHint: 'upstream resolvers, tried in order — the first is primary',
    upstreamPreset: 'Known resolver…',
    upstreamCustom: 'Custom',
    blockingTitle: 'Blocking',
    blockingModeZeroIp: 'Answer with 0.0.0.0 (recommended: fails fast, quiet)',
    blockingModeNxdomain: 'Answer NXDOMAIN (domain does not exist)',
    blockTTL: 'Response TTL (seconds)',
    blockTTLHint: 'how long clients cache a blocked answer',
    safeSearch: 'Enforce Safe Search for everyone',
    safeSearchHint:
      'Google, Bing, DuckDuckGo, and YouTube (moderate) answer with their enforced-safe variants. Devices in bypass groups are exempt.',
    firefoxCanary: 'Keep Firefox on this resolver',
    firefoxCanaryHint:
      "Answers Firefox's use-application-dns.net check with NXDOMAIN — Mozilla's documented signal that this network filters DNS — so Firefox keeps using Minos instead of switching itself to its built-in DNS over HTTPS. Untick to let Firefox decide.",
    privateRelay: 'Block iCloud Private Relay',
    privateRelayHint:
      'Denies the mask.icloud.com hostnames Apple documents for exactly this. Apple devices show "Private Relay is unavailable on this network" and use normal DNS, so Minos can judge their queries. A real privacy trade — off by default.',
    cacheTitle: 'Response cache',
    cacheHint: 'answers repeat queries from memory instead of asking upstream',
    cacheEnabled: 'Enable the response cache',
    cacheMaxEntries: 'Max cached answers',
    cacheMinTTL: 'Minimum TTL (seconds)',
    cacheMinTTLHint: 'short-lived answers are kept at least this long',
    cacheMaxTTL: 'Maximum TTL (seconds)',
    cacheMaxTTLHint: 'no answer is served from cache longer than this',
    cacheServeStale: 'Serve stale answers while refreshing',
    cacheServeStaleHint:
      'if an upstream is slow or down, answer from the expired entry (up to 6 hours old) and fetch a fresh one in the background',
    routesTitle: 'Conditional forwarding',
    routesHint: 'send certain domains to a different resolver (e.g. your router)',
    routesEmpty: 'No routes. All queries use the upstreams above.',
    routesDomains: 'domains (comma-separated)',
    routesDomainsPlaceholder: 'lan, home.arpa, 1.168.192.in-addr.arpa',
    routesNote:
      'Matches the domains and all their subdomains. A route is authoritative: if its resolver fails, the query fails rather than falling back.',
    routesAdd: 'Add route',
    listsTitle: 'Blocklist refresh',
    refreshInterval: 'Refresh interval',
    refreshIntervalHint: 'e.g. 24h, 12h, 6h — minimum 5m',
    querylogTitle: 'Query log',
    retention: 'Keep history (days)',
    ringSize: 'Live buffer size (entries)',
    ephemeralNote: 'Disk logging is off (ephemeral mode) — set in the config file.',
    dbPathNote: (p: string) => `History is stored in ${p}.`,
    apiTitle: 'API access',
    tokenSet: 'An API token is set. The UI and CLI must present it.',
    tokenUnset: 'No API token — anyone on the LAN can use this interface.',
    tokenPlaceholder: 'new API token',
    tokenSave: 'Set token',
    tokenClear: 'Remove token',
    tokenConfirmClear: 'Remove the API token? Anyone on the LAN will be able to manage Minos.',
    listenNote: (dns: string, api: string) =>
      `DNS listens on ${dns}, this interface on ${api}. Listen addresses are set in the config file and need a restart.`,
    notificationsTitle: 'Notifications',
    notificationsHint: 'get told when something on your network changes',
    notificationsNote:
      'Three events, all low-volume: a device makes its first DNS query, an upstream resolver fails or recovers, and (with the update check on) a new release. Nothing is sent unless a destination is set.',
    webhookURL: 'Webhook URL',
    webhookHint: 'each event is POSTed as JSON',
    ntfyURL: 'ntfy topic URL',
    ntfyHint: 'e.g. https://ntfy.sh/my-minos-topic, or your self-hosted ntfy',
    ntfyToken: 'ntfy access token',
    ntfyTokenHint: 'only for protected topics; leave blank otherwise',
    updatesTitle: 'Updates',
    updateCheck: 'Check for new releases once a day',
    updateCheckHint:
      'Asks GitHub for the latest release tag — nothing about you or your network is sent, only the request itself. Off unless you turn it on.',
    updateAvailable: (v: string) => `v${v} available`,
    backupTitle: 'Backup & restore',
    backupHint: 'download or restore the full configuration',
    backupButton: 'Export configuration',
    restoreLabel: 'Restore from a backup',
    restoreHint: 'upload a minos.yaml exported earlier',
    restoreButton: 'Restore configuration',
    restoreConfirm:
      'Replace the entire running configuration with this backup? Listen addresses and query-log storage are kept from the current setup; everything else is overwritten.',
    restoreDone: 'Configuration restored and applied.',
    importTitle: 'Import from Pi-hole or AdGuard Home',
    importHint: 'bring your existing setup across',
    importGravity: 'Pi-hole gravity.db',
    importCustomList: 'custom.list (Local DNS Records)',
    importAdguard: 'AdGuardHome.yaml',
    importOptional: 'optional',
    importButton: 'Import',
    importNote:
      'Imports only add — nothing already configured is removed, and duplicates are dropped. Regex rules and other unsupported entries are listed as skipped. Find gravity.db in /etc/pihole; AdGuardHome.yaml alongside the AdGuardHome binary.',
  },

  token: {
    prompt: 'This instance requires an API token.',
    placeholder: 'API token',
    submit: 'Unlock',
  },
};
