// Package web embeds the built frontend. web/dist is generated by
// `npm run build` (wrapped by `make build`) — never edit it by hand.
package web

import "embed"

//go:embed all:dist
var Dist embed.FS
